[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"

[workspace.dependencies]
reddit-core = { path = "crates/reddit-core" }
ahash = "0.8.11"
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
gjson = "0.8.1"
indicatif = "0.18.3"
petgraph = { version = "0.8.3", features = ["rayon"] }
rayon = "1.11.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
zstd = { version = "0.13.3", features = ["zstdmt"] }
criterion = { version = "0.8.1", features = ["html_reports"] }
simd-json = "0.17.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
codegen-units = 1
lto = "fat"
strip = true

[profile.thin]
inherits = "release"
lto = "thin"
